spring:
  datasource:
    url: jdbc:mysql://localhost/platform
    username: secuapp
    password: secu1234!@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      generate-ddl: true

    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    root: warn

server:
  port: 8082
#    org.hibernate.type: trace